try {
    throw Error('Dedad')
} catch (err) {
    console.log(err)
}
